version: '3'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./project-maven:/opt/project-maven:rw
      - ./project-gradle:/opt/project-gradle:rw
      - ./ansible-maven:/opt/ansible-maven:rw
      - ./ansible-gradle:/opt/ansible-gradle:rw
    tmpfs:
      - /run
      - /run/lock
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
