---
- name: Build and deploy the project
  hosts: localhost
  connection: local
  become: yes

  vars:
    tomcat_version: "10.1.15"
    maven_project_path: /opt/project
    tomcat_webapp_path: "/usr/local/apache-tomcat-{{ tomcat_version }}/webapps"
    war_file_name: ROOT.war

  tasks:
    - name: Build Maven project
      shell: |
        source /etc/profile
        mvn clean package
      args:
        chdir: "{{ maven_project_path }}"

    - name: Remove all files and directories in webapps
      file:
        path: "{{ tomcat_webapp_path }}"
        state: absent

    - name: Recreate the webapps directory
      file:
        path: "{{ tomcat_webapp_path }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: "{{ maven_project_path }}/target/{{ war_file_name }}"
        dest: "{{ tomcat_webapp_path }}/{{ war_file_name }}"
        owner: root
        group: root
        mode: '0644'

    - name: Restart Tomcat service
      systemd:
        name: tomcat
        state: restarted
        enabled: yes
